### ISSUE TITLE
麻烦能给一下sql吗

### ISSUE THREAD

**Issue by stevenliuit** [lamwood/fx_shop#3]
你好能给一下sql吗 单代码跑不起来啊

**Comment by lamwood** [comment]
这个版本太老旧了，不再维护了，准备推出基于Thinkphp5.1框架的新版本

Steven <notifications@github.com> 于2021年1月15日周五 下午6:14写道：

**Comment by stevenliuit** [comment]
求一份 最新的啊 这个跑了下 少好多东西

**Comment by lamwood** [comment]
已经更新到github了，你自己克隆吧
